### ISSUE TITLE
교재 오타.. 

### ISSUE THREAD

**Issue by WOOJOONSIK** [hyunyulhenry/quant_py#1]
1. p85, result = pd.merge(left, right, on="key", how="right")
   -. 오류 -> 결과는 how="left"  결과 
   -. 수정 -> result = pd.merge(left, right, on="key", how="left")
   
2. p86, result = pd.merge(left, right, on="key", how="left")
   -. 오류 -> 결과는 "right" 결과 
   -. 수정 -> esult = pd.merge(left, right, on="key", how="right")

**Comment by hyunyulhenry** [comment]
아 순서가 바꼈네요.
감사합니다.
