### ISSUE TITLE
p.368 페이지 문의

### ISSUE THREAD

**Issue by GritUpward** [hyunyulhenry/quant_py#10]
안녕하세요 만들어주신 교재 너무 잘 보고 있습니다.

14장 포트폴리오 p.368 에 price = pd.read_sql('select * from sample_etf;', con = engine) db에서 저장한 데이터를 불러와 사용하는 것으로 나와있는데
해당 변수인 price 는 사용이 안되고 바로 직전에 dataframe 형태인  prices 변수만  활용이 되더라구요...

혹시 다른 이유가 있는 것인지 궁금합니다.

price로 하려면 어떤 구문을 더 추가해야되는지 궁금합니다.(오류가 발생함)

**Comment by hyunyulhenry** [comment]
아 이거 오타입니다.

`price = pd.read_sql('select * from sample_etf;', con = engine)`
가 아니라
`prices = pd.read_sql('select * from sample_etf;', con = engine)`
로 하면 되고, 
그냥 직전에 다운로드 받은 데이터프레임 그대로 사용해도 됩니다.

**Comment by GritUpward** [comment]
늘 감사드립니다! 좋은 연휴 되세요!
2023년 5월 5일 (금) 오후 9:46, HenryLee ***@***.***>님이 작성:

**Comment by GritUpward** [comment]
알려주신 내용대로 해봤지만 오류가 뜨더라구요 ㅎㅎ
먼가 dataframe 형식에 변화가 있지않을까 생각되는데 tolist를 써야되는지 해봐도 안되긴해서 
(아마 제가 잘못했을 수도 있습니다.. 경험이 부족한지라.. ㅠ)

우선 교재대로 나아갈라고 합니다 ㅎㅎ

감사합니다.

**Comment by sajacaros** [comment]
index가 순번으로 되서 그래요~

db에서 prices 가져온 후
prices.set_index('Date', inplace=True)

해주시면 됩니다.
