### ISSUE TITLE
해외주식(미국) delisted stock 리스트는 어떻게 알 수 있을까요?

### ISSUE THREAD

**Issue by greeksharifa** [hyunyulhenry/quant_py#11]
안녕하세요, 좋은 책 잘 보고 있습니다.

책 265페이지에서 Tiingo의 경우 상장폐지된 종목을 커버한다고 되어 있는데, (미국 주식에 한해서여도 상관없습니다) documentation을 봐도 잘 모르겠어서 질문드립니다.

- 혹시 상장폐지된 종목들의 리스트를 얻을 수 있는 방법이 있나요? 가능하다면 (TICKER, 상장폐지일) 정보를 얻을 수 있으면 좋겠습니다. 
- 티커 변경 이력은 어디서 얻을 수 있을까요? (ex. FB -> META)

감사합니다.

**Comment by hyunyulhenry** [comment]
글쎄요 상폐된 티커를 입력하면 데이터 나오면서 delist = 'Y' 라고 뜨는데
상폐 리스트를 어디서 구하는 지는 모르겠네요

`support@tiingo.com`

팅고측에 이메일 보내시는게 더 정확한 답변 받으실 겁니다.
