### ISSUE TITLE
bt패키지 오류

### ISSUE THREAD

**Issue by mingyuchoii** [hyunyulhenry/quant_py#12]
안녕하세요! 책 보고 공부 중입니다!
Anaconda Prompt에서 pip install bt를 통해 bt패키지를 받으려 했는데 오류가 나와서요!  
  ERROR: Failed building wheel for bt
Failed to build bt
ERROR: Could not build wheels for bt, which is required to install pyproject.toml-based projects
이러한 오류가 나왔는데 파이썬 버전 문제일까요?? C:\Users\user> python를 통해서 버전을 확인하면 Pthon 3.10.9로 나옵니다!

**Comment by hyunyulhenry** [comment]
https://stackoverflow.com/questions/53204916/what-is-the-meaning-of-failed-building-wheel-for-x-in-pip-install

여기 나오는 방법들 참고해주시기 바랍니다.

**Comment by mingyuchoii** [comment]
Visual Studio에서 C++ 다운 받아서 해결했습니다! 감사합니다~!

**Comment by sseungho** [comment]
> Visual Studio에서 C++ 다운 받아서 해결했습니다! 감사합니다~!

C++ 최신 버전으로 업데이트 했는데 여전히 안되네요...ㅠㅜ
