### ISSUE TITLE
pymysql, tqdm 패키지 사용에 대하여...

### ISSUE THREAD

**Issue by Daeyoung428** [hyunyulhenry/quant_py#14]
도서와 인터넷 강의를 통하여 잘 학습하다.

Chapter 10 국내 주식 데이터 수집의 import pymysql(234 Page)부터 Spyder를 실행하면
"ModuleNotFoundError: No module named 'pymysql'"를 발생하여
Anaconda Prompt로 pip install pymysql하면 "Requirement already satisfied: pymysql in c:\users\david\appdata\roaming\python\python310\site-packages (1.0.3)"로 되어 있습니다.

아주 기초적인 부분일지 모르겠으나 어떠한 이유인지 찾을 수 없군요.

**Comment by hyunyulhenry** [comment]
아나콘다의 파이썬 환경이랑 스파이더에서 사용하는 파이썬이 달라서 사용하는 문제입니다.
스파이더에서 아나콘다 가상환경 설정해주면 해결이 됩니다.
아니면 싹 지우고 아나콘다를 처음부터 재설치해도 해결이 됩니다.

---------

파이썬과 같은 인터프리터 언어에서는 패키지의 가용성이 인터프리터의 인스턴스나 환경에 따라 달라질 수 있습니다. Anaconda는 이 문제를 처리하기 위해 가상 환경(virtual environments)을 사용하며, 각 환경은 각자의 패키지 세트를 가집니다.

Anaconda Prompt에서 패키지가 설치되었다고 나오는데, Spyder에서는 패키지가 없다고 나온다면, 아마도 두 환경이 다른 가상 환경을 사용하고 있는 것일 수 있습니다.

다음은 이 문제를 해결하는 방법 중 하나입니다:

1. Anaconda Prompt에서 사용하는 가상 환경의 이름을 확인합니다. Anaconda Prompt에서 conda env list를 입력하면 현재 가상 환경의 리스트가 나타나며, *가 표시된 곳이 현재 활성화된 가상 환경입니다.
2. Spyder에서 동일한 가상 환경을 사용하도록 설정합니다. Spyder의 설정에서 Python 인터프리터를 변경할 수 있습니다. Python 인터프리터의 경로를 앞서 확인한 가상 환경의 경로로 변경합니다. 가상 환경의 Python 인터프리터 경로는 대체로 다음과 같습니다: Anaconda3/envs/YourEnvironmentName/bin/python.
3. 설정을 변경한 후, Spyder를 재시작하면 해당 가상 환경에서 사용 가능한 패키지를 사용할 수 있게 됩니다.

이 방법을 통해 Spyder에서도 Anaconda Prompt에서 설치한 패키지를 사용할 수 있게 될 것입니다.

**Comment by Daeyoung428** [comment]
친절한 설명으로 잘 이해하였으며 해결되었습니다.

파이썬에 익숙하지 않은데도 어려움 없이 도서와 강의를 통하여 학습을 진행할 수 있음에 감사합니다.
