### ISSUE TITLE
p.388 yfinance 질문드립니다

### ISSUE THREAD

**Issue by HYU-hyeno** [hyunyulhenry/quant_py#16]
1.
import talib
import yfinance as yf

stock_data = yf.download('^GSPC')

다음 코드를 실행하면 결과가 다음과 같이 나옵니다.
[*********************100%***********************]  1 of 1 completed
1 Failed download:
['^GSPC']: TypeError('super(type, obj): obj must be an instance or subtype of type')

이렇게 나오고 stock_data 에 값이 저장되지 않습니다.
기초적인 것인데 어디서 잘못된건지 모르겠습니다..

2.
책에서는 조금 다른 방법으로 데이터를 받아오길래 다른 방법으로 시도해보았습니다.
import pandas_datareader as web

stock_data = web.DataReader('^GSPC', 'yahoo')

결과:
Traceback (most recent call last):

  Input In [25] in <cell line: 3>
    stock_data = web.DataReader('^GSPC', 'yahoo')

  File ~\anaconda3\lib\site-packages\pandas\util\_decorators.py:207 in wrapper
    return func(*args, **kwargs)

  File ~\anaconda3\lib\site-packages\pandas_datareader\data.py:370 in DataReader
    return YahooDailyReader(

  File ~\anaconda3\lib\site-packages\pandas_datareader\base.py:253 in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))

  File ~\anaconda3\lib\site-packages\pandas_datareader\yahoo\daily.py:153 in _read_one_data
    data = j["context"]["dispatcher"]["stores"]["HistoricalPriceStore"]

TypeError: string indices must be integers
이처럼 다른방법도 오류가 나네요..

**Comment by hyunyulhenry** [comment]
![image](https://github.com/hyunyulhenry/quant_py/assets/20567847/9e10b15f-f870-463c-a9c4-784ba5a3feb9)
저는 잘 되는데요...

(pandas_datareader 패키지는 더 이상 작동하지 않습니다.)

**Comment by HYU-hyeno** [comment]
pandas datareader는 작동 안하는 거였군요,, 위에 질문은 해결했습니다! 감사합니다
