### ISSUE TITLE
파이썬 sql 연결 과정

### ISSUE THREAD

**Issue by dongd1122** [hyunyulhenry/quant_py#17]
import pymysql

con = pymysql.connect(
    user= 'root',
    passwd= '1234',
    host= '127.0.0.1',
    db= 'shop',
    charset= 'utf8'
)
이 부분에서 
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods 이런 오류가 발생합니다.
cryptography를 설치해야 한다고 해서 프롬프트에서 설치하였는데,
프롬프트에선 cryptography가 이미 설치되었다고 뜨는데 vscode에서는 계속 위 에러가 발생합니다.
혹시 이 문제와 관련하여 해결방안이 있을까요?
감사합니다.

**Comment by hyunyulhenry** [comment]
프롬프트에서 사용하는 파이썬 환경이랑, vscode에서 사용하는 파이썬 환경이 달라서 그럴겁니다.
vs code 내에서 바로 패키지 설치해보시지요
