### ISSUE TITLE
p.372 riskfolio의 plot_bar 에러

### ISSUE THREAD

**Issue by mankic** [hyunyulhenry/quant_py#18]
`w = port.optimization(model=model, rm=rm, obj=obj, rf=rf, l=l, hist=hist)`

가중치 계산 코드까지는 실행되어서 결과가 데이터프레임으로 잘 저장이 되지만

`rp.plot_bar(w=w)`

코드를 실행하면

AttributeError: 'DataFrame' object has no attribute 'append'
오류가 발생합니다.

riskfolio-lib 의 3.3.0 버전과 최신버전인 4.4.0 모두 같은 에러가 발생하였고

해당 오류에 대해 검색해보았을땐 
pandas 2.0 버전 부터 append 기능이 사라졌기 때문이라고 알게되어
pandas 1.3.1 버전으로 다운그레이드하여 실행해보았지만 
이렇게 하니 yfinance와 버전이 맞지 않는것 같아 yf.download가 실행되지 않았습니다.

어떻게 해결 할 수 있을까요??

**Comment by hyunyulhenry** [comment]
1. https://riskfolio-lib.readthedocs.io/en/latest/risk.html 보시면 risk contribution 을 직접 계산할 수 있는 함수가 있습니다. 수기로 계산한다음에 pandas plot 기능으로 그릴 수 있겠네요.
2. 해당 패키지 제작자 깃허브에 가셔서 문제를 올리고 고쳐주길 기다리면 됩...

**Comment by mankic** [comment]
> 1. https://riskfolio-lib.readthedocs.io/en/latest/risk.html 보시면 risk contribution 을 직접 계산할 수 있는 함수가 있습니다. 수기로 계산한다음에 pandas plot 기능으로 그릴 수 있겠네요.
> 2. 해당 패키지 제작자 깃허브에 가셔서 문제를 올리고 고쳐주길 기다리면 됩...
