### ISSUE TITLE
P227질문드립니다. 간단한건데 왜ㅠㅠ

### ISSUE THREAD

**Issue by hyung2s** [hyunyulhenry/quant_py#19]
mktId : 'STK',
...     trdDd : 20230714,
...     money : '1',
...     csvxls_isNo : 'false',
...     name : 'fileDown',
...     url : 'dbms/MDC/STAT/standard/MDCSTAT03901'
... }
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'mktId' is not defined

**Comment by hyunyulhenry** [comment]
날짜는 20230714가 아니라 '20230714' 로 캐릭터 타입으로 입력해야 됩니다.
