### ISSUE TITLE
p224~p228 결과문의드립니다.

### ISSUE THREAD

**Issue by EddieLimJ** [hyunyulhenry/quant_py#20]
한국거래소 사이트에서 산업별 현황 데이터를 저장하는 예제를 수행하면 아래와 같은 결과가 나옵니다.
(테이블 제목만 나오고 내용이 출력되지 않습니다.)
잘은 모르겠지만, referer 정책이 바뀌거나 뭔가 제 쪽의 접근을 봇으로 인식한건 아닐까 싶긴한데..
제가 초보라 저자님께 문의드립니다.

![결과](https://github.com/hyunyulhenry/quant_py/assets/140955119/72339fbb-019f-46bd-b910-ff83421730d0)

**Comment by hyunyulhenry** [comment]
![image](https://github.com/hyunyulhenry/quant_py/assets/20567847/42e512b3-41ae-4c2c-ac58-8fca4d631f46)

바뀐거 없고 잘 작동합니다
query 부분 입력값 잘못 입력하셨을 겁니다
