### ISSUE TITLE
p.206쪽 셀레늄 설치 문의드립니다.

### ISSUE THREAD

**Issue by whtkgu** [hyunyulhenry/quant_py#21]
![image](https://github.com/hyunyulhenry/quant_py/assets/112760509/d4ffdac4-c7a8-4789-836e-290dff744049)
![image](https://github.com/hyunyulhenry/quant_py/assets/112760509/0a76b118-f9ff-41ed-a050-8241ff880b23)
크롬에서 진행하고 있는데 계속 오류가 나고 여기서 다음으로 넘어가지가 않는데.. 왜그럴까요..

**Comment by hyunyulhenry** [comment]
셀레니움이 업데이트 되어서
 이제 크롬 드라이버를 다운받지 않아도 됩니다
`webdriver.Chrome()` 만 해도 됩니다.

https://www.inflearn.com/questions/932263/%ED%81%AC%EB%A1%AC%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B8%8C-%EC%8B%A4%ED%96%89-%EC%98%A4%EB%A5%98

**Comment by whtkgu** [comment]
![image](https://github.com/hyunyulhenry/quant_py/assets/112760509/bae9f769-e4de-4377-a1e5-719e42e911b9)
이제는 다른 오류코드가 나오는데 해결방법이 있을까요..

**Comment by hyunyulhenry** [comment]
저도 일반적인 오류에 대해 알지 패키지별 모든 오류에 대해서는 알 수 없습니다.
각종 오류는 복사하신 후 구글에 검색하시는게 훨씬 빠르게 해결이 가능할 듯 합니다.
