### ISSUE TITLE
교재 p208 검색창 접근 오류 문제

### ISSUE THREAD

**Issue by Hangseop** [hyunyulhenry/quant_py#22]
안녕하세요
2가지 질문 드립니다.

1. 뒤로가기 실행을 위해 driver.back() 명령문을 실행하면 에러는 나지 않는데 열었던 네이버 '뉴스' 페이지에서 naver home 으로 넘어가지 않습니다.  네어비 홈에서 뉴스로 진입할 때에 같은 페이지가 '뉴스'로 변경 되는 것이 아니고 뉴스 탭이 별도로 생기면서 뒤로가기 버튼이 활성화되지 않아서 인 것 같은데 해결 방법은 무엇인지요

2. 검생창으로 실행하는 명령
   driver.find_element(By.CLASS_NAME, value = 'input_text').send_keys('퀀트 투자 포트폴리오 만들기') 을 실행하면 다음과 같은 에러가 발생합니다. 
   NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".input_text"}
  (Session info: chrome=115.0.5790.171); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception 

워낙 초보라서 해당 페이지에 가서 확인해 보아도 이해가 가지 않아 질문 드립니다. 해결 방법을 부탁드립니다.

**Comment by hyunyulhenry** [comment]
1. _blank 로 안열리게 코드 수정하면 됩니다.

```
from selenium import webdriver

driver = webdriver.Chrome()
driver.get("YOUR_URL_HERE")

# 링크 요소를 찾는다
link = driver.find_element_by_xpath("YOUR_XPATH_HERE")

# 링크의 target 속성을 _self로 변경
driver.execute_script("arguments[0].setAttribute('target', '_self');", link)

# 링크 클릭
link.click()
```

2. 네이버 페이지 바뀌면서 엘레멘트가 다 바뀌었을 겁니다. 개발자도구 화면 열어서 그에 맞게 수정하시면 됩니다.
