### ISSUE TITLE
dart 고유 번호 불러오기 관련 질문드립니다.

### ISSUE THREAD

**Issue by ssong2820** [hyunyulhenry/quant_py#24]
import keyring

keyring.set_password('xxxxxxxxxxxx','email주소','password')

import keyring
import requests as rq
from io import BytesIO
import zipfile

api_key = keyring.get_password('xxxxxxxxxxxx', 'Kim')
codezip_url = f'''https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key={api_key}'''
codezip_data = rq.get(codezip_url)
print(codezip_data.headers)

상기와 같이 따라하면 하기와 같이 나와 책과 다르게 나오네요
{'Connection': 'keep-alive', 'Set-Cookie': 'WMONID=gnNui8TZXqd; Expires=Wed, 11-Sep-2024 16:41:10 GMT; Path=/', 'Date': 'Tue, 12 Sep 2023 07:41:10 GMT', 'Content-Type': 'application/xml;charset=UTF-8', 'Transfer-Encoding': 'chunked'}

api 주소만 따로 떼서 f stirng으로 넣지않고 바로 넣어 url 불러오면 책과 정상적으로 나오는데...
어디가 잘못된건지 알 수 있을까요?

**Comment by hyunyulhenry** [comment]
f스트링으로 만든 url이랑 원래 url이랑 비교해보면 어디 문제인지 확인 가능할듯합니다

**Comment by ssong2820** [comment]
keyring.set_password('dart_api_key','user_id','password')
설정하고
keyring.get_password('dart_api_key','user_id') 하게되면
api_key 값은 password값을 불러오게 되는데
책에는 하기 처럼 되어 있어서 attachment_filename 값이 안불러와지는 거로 보이는데....
책 내용이 맞는건가요??
codezip_url = f'''https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key={api_key}'''
