### ISSUE TITLE
고유 번호 다운로드 문의

### ISSUE THREAD

**Issue by ssong2820** [hyunyulhenry/quant_py#25]
고유 번호 다운로드 문의 드려요
특정 시점 부터 안되는 게 많네요 ㅠㅠ

하기와 같이 실행했는데, import Error 가 발생하네요...
코딩상 문제인지 패키지 문제인지 몰라 문의드립니다.

ImportError: Unable to find a usable engine; tried using: 'sqlalchemy'.
A suitable version of sqlalchemy is required for sql I/O support.
Trying to import the above resulted in these errors:
 - Pandas requires version '1.4.16' or newer of 'sqlalchemy' (version '1.4.7' currently installed).

import keyring
import requests as rq
from io import BytesIO
import zipfile

codezip_url = f'''https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key=?????????'''
codezip_data = rq.get(codezip_url)

codezip_file = zipfile.ZipFile(BytesIO(codezip_data.content))

import xmltodict
import json
import pandas as pd

code_data = codezip_file.read('CORPCODE.xml').decode('utf-8')
data_odict = xmltodict.parse(code_data)
data_dict = json.loads(json.dumps(data_odict))
data = data_dict.get('result').get('list')
corp_list = pd.DataFrame(data)

import pymysql
from sqlalchemy import create_engine

corp_list = corp_list[~corp_list.stock_code.isin(
    [None])].reset_index(drop=True)

engine = create_engine('mysql+pymysql://root:???????@127.0.0.1:3306/stock_db')
con = pymysql.connect(user='root',
                      passwd='???????',
                      host='127.0.0.1',
                      db='stock_db',
                      charset='utf8')
mycursor = con.cursor()

corp_list.to_sql(name='dart_code', con=engine, index=True, if_exists='replace')

engine.dispose()
con.close()

**Comment by hyunyulhenry** [comment]
`Pandas requires version '1.4.16' or newer of 'sqlalchemy' (version '1.4.7' currently installed).`

텍스트 안에 해결책이 적혀있습니다.

**Comment by ssong2820** [comment]
감사합니다.
