### ISSUE TITLE
교재 구매했습니다. 본 교재에서 사용하신 코드들은 어떤 editor를 사용하시는지 궁금합니다.

### ISSUE THREAD

**Issue by jaesungb** [hyunyulhenry/quant_py#26]
jupyternotebook, spyder, pycharm 등.
교재에 명시된 바가 없어 질의드립니다. ㅠㅠ

**Comment by hyunyulhenry** [comment]
에디터는 도구일 뿐이라 본인이 편한거 쓰면 됩니다
책은 주피터노트북으로 썼고
코드 검증은 스파이더에서 했습니다
