### ISSUE TITLE
17장 증권사 API 연결과 매매하기 문의드립니다.

### ISSUE THREAD

**Issue by superdupermulti17** [hyunyulhenry/quant_py#3]
428페이지에 아래 코드에서 오류발생하고 있습니다.
# 접근토큰 발급
res = requests.post(url, headers=headers, data=json.dumps(body))
access_token = res.json()['access_token']
KeyError: 'access_token'

res.json()는 이상없고 res.json()['access_token']에서 오류가 발생하는데 확인 요청드립니다.

**Comment by hyunyulhenry** [comment]
![key](https://user-images.githubusercontent.com/20567847/223883230-3cfffd09-64bb-4b07-bfd8-3b5b60421175.png)

정상 작동하고 코드에는 이상이 없습니다.

1. 모의투자 도메인에 실제투자 API Key를 넣었다거나 반대가 아닌지 확인해보세요.
2. `res.json()` 만 출력해서 오류가 뭐뜨는지 확인해보세요.

**Comment by MANAJIM** [comment]
안녕하세요. 저도 윗분과 같은 오류가 발생하고 있습니다.
몇 번이나 코드를 살펴보았는데 아래와 같이 오류가 생기고 있어요.
이유가 뭔지 잘 모르겠습니다...
![image](https://github.com/hyunyulhenry/quant_py/assets/125785210/0c4e7267-61e9-4bd4-b938-5730aa10a9d6)
