### ISSUE TITLE
keyring.get_password 관련 질문드립니다.

### ISSUE THREAD

**Issue by ssong2820** [hyunyulhenry/quant_py#34]
import keyring

keyring.set_password('dart_api_key', 'User Name', 'Password')

api_key = keyring.get_password('dart_api_key', 'Henry')
codezip_url = f'''https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key={api_key}'''

안녕하세요
상기처럼 
keyring.set_password 한 후에
api_key = keyring.get_password 로 받아오는 데,
그렇게 되면 api_key = 'Password' 값이 되서 

codezip_url = f'''https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key={api_key}'''  
상기 값이 제대로 안먹는게 아닌가요?
계속 안되어서
{api_key} ==> 'dart_api_key'를 직접 입력해서 실행하니 먹히던데...
제가 잘못 이해하고 있는건지 문의드립니다.
감사합니다.

**Comment by hyunyulhenry** [comment]
keyring.set_password('dart_api_key', 'User Name', 'Password')

api_key = keyring.get_password('dart_api_key', 'Henry')

이걸 그대로 붙여 넣으시면 당연히 안되고 본인의 user name을 입력 하셔야 되겠죠....
저 코드에서 저장은 `User Name` 으로 하고 불러오는건 `Henry` 로 되어있으니 당연히 저장된 API Key가 없으니..
