### ISSUE TITLE
판다스 최신버전에서 groupby와 agg() 에러 문의드려요

### ISSUE THREAD

**Issue by YK8405** [hyunyulhenry/quant_py#36]
안녕하세요..

교재 99페이지와 100페이지에 나와있는

df.groupby(['species','sex']).mean() 코드와

df.groupby(['species']).agg(['max','min'])코드가 판다스 최신버전에서는 에러가 나오는데 해결 방법이 있을까요?

아마 판다스 버전 2.0 이하에서는 잘 되는것 같은데 그 이상 버전에서는 에러가 나네요..

**Comment by hyunyulhenry** [comment]
구버젼에는 `mean()` 이나 `agg(['max','min'])` 를 하면 숫자 타입의 열만 알아서 계산이 됐는데
신버젼 부터는 `df.groupby(['species', 'sex'])['bill_depth_mm'].mean()` 이렇게 숫자열만 선택한 다음에 function을 입력해야 실행이 되네요.
