### ISSUE TITLE
문법에러 문의 드립니다.

### ISSUE THREAD

**Issue by hyung2s** [hyunyulhenry/quant_py#37]
책 p231에 
코스피 코스닥  데이터 합치기에서   kor_ticker = pd.merge(krx_sector,
                                                                                               krx_ind,
                                                                                               on=krx_sector.columns.intersection(
                                                                                                       krx_ind.columns).tolist(),
                                                                                                how='outer')
                                                           kor_ticker.head()를 실행하면 "문법에러"가 나타납니다.  어떻게된 것인지 가르쳐 주십시요

**Comment by hyunyulhenry** [comment]
이렇게 봐서는 알 수가 없습니다.
코드는 잘 작동합니다.
