### ISSUE TITLE
파이썬에서 sql 연결하기

### ISSUE THREAD

**Issue by wonnykim2** [hyunyulhenry/quant_py#38]
import pymysql

con = pymysql.connect(
    user='root',
    passwd='1234',
    host='127.0.0.1',
    db='shop',
    charset='utf8'
)
파이썬에서 sql db에 접속하는데 위 쿼리를 실행하는데
아래같은 deny 메시지가 뜨네요. 

OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

어떻게 해결할 수 있을련지요..

**Comment by hyunyulhenry** [comment]
GPT 답변입니다.

---

OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)") 오류는 MySQL 데이터베이스에 접속할 때 발생하는 권한 관련 문제입니다. 이 오류를 해결하기 위해 몇 가지 방법을 시도해 볼 수 있습니다.

비밀번호 확인: 가장 먼저 확인해야 할 것은 제공한 비밀번호가 정확한지 여부입니다. passwd='1234'가 실제 MySQL 'root' 사용자의 비밀번호와 일치하는지 확인하세요.

사용자 권한 확인: MySQL에 'root' 사용자가 외부 접속을 허용하는 권한을 갖고 있는지 확인하세요. MySQL 콘솔에 로그인한 후 다음 명령어를 실행하여 권한을 확인할 수 있습니다:

```
Copy code
SELECT user, host FROM mysql.user;
```
이 명령어는 모든 사용자와 그들의 호스트를 보여줍니다. 'root' 사용자가 'localhost'에서 접속할 수 있는지 확인하세요.

방화벽 설정 확인: 서버의 방화벽 설정이 MySQL 접속을 차단하고 있지 않은지 확인하세요.

MySQL 서버 상태 확인: MySQL 서버가 실행 중이고, 지정한 호스트와 포트(host='127.0.0.1')에서 수신 대기하고 있는지 확인하세요.

사용자 권한 부여: 만약 'root' 사용자에게 외부 접속 권한이 없다면, 다음과 같은 SQL 명령어를 사용하여 권한을 부여할 수 있습니다:

```
Copy code
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'your_password';
FLUSH PRIVILEGES;
```
여기서 'your_password'는 'root' 사용자의 비밀번호로 바꿔야 합니다.
