### ISSUE TITLE
퀀트투자 포트폴리오 만들기 질문 입니다.

### ISSUE THREAD

**Issue by stonic0723** [hyunyulhenry/quant_py#40]
책과 함께 유투브 동영상을 보면서 지식을 알려주심에 감사 드립니다.
실습을 해 가면서 이해가 되지 않고 또, 코드가 제대로 동작 하지 않아 두가지 질문 드립니다.

**1. 230페이지** 
krx_ind = rq.post(down_url, {'code': otp}, headers=headers)  에서 'code'는 주식의 코드를 의미하는지요?

2. fnguide에서 전체 재무제표를 가져오기 하면 전체종목이 나오는것이 아닌거 같은데 fnguide 에서 제공안하는 종목들이 많은가요?  많다면 네이버 같은곳에서 재무제표를 가져오면 될거 같은데 fnguide와 차이점은 무엇인지 알고 싶습니다.

**Comment by hyunyulhenry** [comment]
1. OTP 코드입니다. 제가 입력한게 아니라 krx에서 설정한 파라미터입니다.
2. 보통주는 전체종목 나옵니다. 네이버도 fnguide 산하인 wise 데이터 계약해서 보여주기 때문에 값은 거의 같습니다

**Comment by stonic0723** [comment]
감사합니다. 앞으로도 좋은 저서 기대합니다. 즐거운 명절 보내세요~~~
