### ISSUE TITLE
모멘텀 포트폴리오 구하기 324페이지 질문입니다.

### ISSUE THREAD

**Issue by stonic0723** [hyunyulhenry/quant_py#41]
안녕하세요 선생님.
코드를 하나하나 따라하다 보니 궁금증이 많아 자꾸 질문의 글을 드립니다.

324페이지의 모멘텀 포트폴리오 코드를 따라하다  return 결괏값들이  수익률이 너무 괴리가 있어서 보니 다음과 같은 문제에 부딛쳤습니다.

과거 데이터 2022년12월28일  인바이오젠(종가 16320원) 아이오케이(종가 9061원) 시티랩스(9589원) 이었습니다. 그런데, 이 종목들이 전부 감자를 하여 과거 주가 데이터를 받아보니 수정주가로 되어 인바이오(816원) 아이오케이(425원) 시티랩스(592원) 으로 되어 2023년12월29일 주가로 수익률을 계산하니 전부 수익률 상위권 입니다. 

현실은 기업이 감자를 할 정도로 나쁜 기업의 수익률이 수정주가로 인해 수익률 상위권으로 나타나면 모멘텀으로 투자를 했을때 의미가 없을거 같습니다.  이렇듯 과거 주가는 수정주가로 인해 감자전 주가를 반영하지 못해 모멘텀 순위가 바르게 나타나지 않을때 어떻게 하면 모멘텀 투자에 부합되는 코딩방법이 있는지 알고 싶습니다.

언제나 건승 하시고, 앞으로도 좋은 책 출간을 바랍니다.

**Comment by hyunyulhenry** [comment]
원래 감자는 수정주가에 반영하면 안되는데 네이버가 잘못 보여주고 있습니다.
야후 파이낸스에서 아이오케이 주가를 보면 과거값도 감자전 기준으로 나옵니다.
사실 제가 회사에서 쓰는 글로벌 DB도 감자는 수정주가에 포함시키지 않는데
이런건 크롤링 기반으로 데이터를 쓰면 어쩔수 없는 현상입니다.

프로페셔널 하게는
1. 일반주가 
2. 수정계수 
3. 1 X 2 통해서 수정주가 계산
하면 되는데 엄청난 노가다죠

https://finance.yahoo.com/quote/078860.KQ/chart?p=078860.KQ#eyJpbnRlcnZhbCI6ImRheSIsInBlcmlvZGljaXR5IjoxLCJ0aW1lVW5pdCI6bnVsbCwiY2FuZGxlV2lkdGgiOjEsImZsaXBwZWQiOmZhbHNlLCJ2b2x1bWVVbmRlcmxheSI6dHJ1ZSwiYWRqIjp0cnVlLCJjcm9zc2hhaXIiOnRydWUsImNoYXJ0VHlwZSI6ImxpbmUiLCJleHRlbmRlZCI6ZmFsc2UsIm1hcmtldFNlc3Npb25zIjp7fSwiYWdncmVnYXRpb25UeXBlIjoib2hsYyIsImNoYXJ0U2NhbGUiOiJsaW5lYXIiLCJwYW5lbHMiOnsiY2hhcnQiOnsicGVyY2VudCI6MSwiZGlzcGxheSI6IjA3ODg2MC5LUSIsImNoYXJ0TmFtZSI6ImNoYXJ0IiwiaW5kZXgiOjAsInlBeGlzIjp7Im5hbWUiOiJjaGFydCIsInBvc2l0aW9uIjpudWxsfSwieWF4aXNMSFMiOltdLCJ5YXhpc1JIUyI6WyJjaGFydCIsIuKAjHZvbCB1bmRy4oCMIl19fSwic2V0U3BhbiI6bnVsbCwibGluZVdpZHRoIjoyLCJzdHJpcGVkQmFja2dyb3VuZCI6dHJ1ZSwiZXZlbnRzIjp0cnVlLCJjb2xvciI6IiMwMDgxZjIiLCJzdHJpcGVkQmFja2dyb3VkIjp0cnVlLCJyYW5nZSI6bnVsbCwiZXZlbnRNYXAiOnsiY29ycG9yYXRlIjp7ImRpdnMiOnRydWUsInNwbGl0cyI6dHJ1ZX0sInNpZ0RldiI6e319LCJzeW1ib2xzIjpbeyJzeW1ib2wiOiIwNzg4NjAuS1EiLCJzeW1ib2xPYmplY3QiOnsic3ltYm9sIjoiMDc4ODYwLktRIiwicXVvdGVUeXBlIjoiRVFVSVRZIiwiZXhjaGFuZ2VUaW1lWm9uZSI6IkFzaWEvU2VvdWwifSwicGVyaW9kaWNpdHkiOjEsImludGVydmFsIjoiZGF5IiwidGltZVVuaXQiOm51bGwsInNldFNwYW4iOm51bGx9XSwic3R1ZGllcyI6eyLigIx2b2wgdW5kcuKAjCI6eyJ0eXBlIjoidm9sIHVuZHIiLCJpbnB1dHMiOnsiaWQiOiLigIx2b2wgdW5kcuKAjCIsImRpc3BsYXkiOiLigIx2b2wgdW5kcuKAjCJ9LCJvdXRwdXRzIjp7IlVwIFZvbHVtZSI6IiMwMGIwNjEiLCJEb3duIFZvbHVtZSI6IiNmZjMzM2EifSwicGFuZWwiOiJjaGFydCIsInBhcmFtZXRlcnMiOnsid2lkdGhGYWN0b3IiOjAuNDUsImNoYXJ0TmFtZSI6ImNoYXJ0IiwicGFuZWxOYW1lIjoiY2hhcnQifX19fQ--
