### ISSUE TITLE
global 주가 다운받기 에서 try: except: 코드 부분 질문입니다.

### ISSUE THREAD

**Issue by VMZO** [hyunyulhenry/quant_py#42]
책 페이지 282 에서
try: except: 부분 이해가 안가서 질문드립니다.

이페이 코드 실행하면 
error_list 안에 다운로드 성공한 ticker 들이 있고, 다운로드 실패한 ticker 들은 안보입니다.

코드는 맞는것 같은데 이해가 안갑니다.
부탁드립니다^^

**Comment by hyunyulhenry** [comment]
글만 봐서는 알수가 없네요
