### ISSUE TITLE
10.5.1 재무제표 다운로드 질문

### ISSUE THREAD

**Issue by rhkqnsqkf** [hyunyulhenry/quant_py#43]
248쪽 파이썬 코드에서 i가 돌아가면서 url이 바뀌고 pd.read_html()로 계속 크롤링을 하는데 마지막 줄에 list comprehension으로 쓴 반복문에서 time.sleep()을 쓰지 않아도 되나요?

**Comment by hyunyulhenry** [comment]
아뇨 여러 페이지 크롤링시 슬립은 무조건 해야 합니다.
그렇지 않으면 IP 차단당합니다.

![image](https://github.com/hyunyulhenry/quant_py/assets/20567847/e7181c8e-9618-4324-ac10-13e197115a02)

**Comment by rhkqnsqkf** [comment]
![WhaleScreenCapture-20240126-113322](https://github.com/hyunyulhenry/quant_py/assets/129239649/6e877551-b153-416f-93f1-c4f19500f871)
그런데 책에 보면 time.sleep()은 없는데요? 사진은 github에서 캡쳐한 것입니다.

**Comment by hyunyulhenry** [comment]
이건 예제로 한 종목만 돌려보는거라 슬립이 필요가 없고

전 종목 for loop 도는 부분에는 슬립을 줬습니다

**Comment by rhkqnsqkf** [comment]
아 그렇네요. list comprehension에서는 i가 변하지 않죠. 착각했습니다. 알려주셔서 감사합니다.
