### ISSUE TITLE
안녕하세요 교수님. 질문드립니다.

### ISSUE THREAD

**Issue by metamelon** [hyunyulhenry/quant_py#45]
여기에 질문을 올리는 걸 모르고 유튜브에 올려놓았네요.

영상은 잘 보고 있습니다. 좋은 교육 영상 감사드립니다. 교수님 영상을 보고 따라하다가

WICS 기준 섹터정보 크롤링 파트에서 biz_day를 생성하기 위해 다음과 같은 코드를 작성했는데 경로가 잘못되었다는 걸로 계속 나옵니다.
제가 전공자가 아니다보니 생각보다 쉽지 않군요.

url = 'https://www.wiseindex.com/index#/G10'
data = rq.get(url)
data_html = BeautifulSoup(data.content)
parse_day = data_html.select_one(
    '#ng-app > div > div > div.col-xs-9.contentsBox > div.ng-scope > div:nth-child(3) > input').text

시간 괜찮으실때 답변 부탁드리겠습니다. 감사합니다.

**Comment by kimhankyeol** [comment]
url = 'https://www.wiseindex.com/index#/G10'
data = rq.get(url)
아래와 같이 하시면 나올거 같아요
data_html = BeautifulSoup(data.content)
parse_day = data_html.select_one(
'#ng-app > div > div > div.contentsBox > p:nth-of-type(2)').text

import re
biz_day = re.findall('[0-9]+', parse_day)
biz_day = "".join(biz_day)

**Comment by metamelon** [comment]
네. 답변 감사드립니다. 다시 한 번 해보겠습니다.
