### ISSUE TITLE
최근 영업일 크롤링

### ISSUE THREAD

**Issue by rhkqnsqkf** [hyunyulhenry/quant_py#46]
질문을 작성하는 오늘은 3월 16일이고 최근 영업일은 3월 15일입니다. 그런데 네이버 증권 증시자금동향에서 크롤링하는 최근 영업일은 3월 13일입니다. 왜 가장 최근인 영업일을 크롤링하지 않고 이틀 전 날짜를 크롤링하나요?

그리고 재무제표를 크롤링한 결과에서 삼성전자의 자본을 보면 실제 사이트에서 본 금액과 달리 마지막 자릿수에서 반올림되어있던데 이건 왜 그런 건가요? 당기순이익, 매출액, 영업활동으로인한현금흐름은 그렇지 않은 것을 보면 큰 수는 반올림이 되는 것 같아요.

**Comment by hyunyulhenry** [comment]
네이버 데이터가 크롤링하기 편해서 그렇습니다. 3월 15일자 데이터를 크롤링할 수 있는 곳이 있으면 써도 상관없습니다.

반올림은 단순히 벤더들 정책입니다.
