### ISSUE TITLE
10.2.2 개별종목 지표 크롤링 부분 - 선행EPS 컬럼 크롤링 불가

### ISSUE THREAD

**Issue by Yoodahun** [hyunyulhenry/quant_py#48]
안녕하세요 @hyunyulhenry 님.

10.2.2 개별종목 지표 크롤링 부분에서 선행EPS 컬럼이 존재하지않아 크롤링이 불가능한 이슈가 있습니다.

KRX들어가봤는데 선행EPS컬럼이 어느순간 삭제된 것 같더라구요.
저는 일단 크롤링 후 쿼리 저장부분에서 `null`값을 박아서 넣어주고있고, 233쪽 컬럼 재정의 부분에서 `선행EPS` 컬럼을 제거해주고있습니다.

확인해보시고 대응방안 알려주시면 좋을 것 같습니다.. 

http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201

<img width="938" alt="image" src="https://github.com/hyunyulhenry/quant_py/assets/26598844/fefab1f1-51ae-4ea0-904e-5d230d334344">

**Comment by hyung2s** [comment]
안녕하세요 저도 이 부분이 막혀 있는데 혹시 답을 얻거든 공유 부탁드립니다.

**Comment by kimhankyeol** [comment]
도움이 될지는 모르겠지만 답변 올립니다.
 네이버 증권 사이트에 들어가셔서 종목 검색 후 추정 PER 부분을 보시면 올해 예상 EPS에 대한 값을 계산하실 수 있을것 같습니다. 
미래에 대한 예측이고 여러 분석가가 분석하여 기댓값을 제시하기 때문에 네이버 및 증권사별로 상이할것 같습니다.
 컨센서스를 확인해서 참고만 하면 될것 같습니다.

**Comment by H9-Develop** [comment]
네이버 증권 사이트에 들어가셔서 종목 검색 후 추정 PER 부분을 보시면 올해 예상 EPS에 대한 값을 계산하실 수 있을것 같습니다.
미래에 대한 예측이고 여러 분석가가 분석하여 기댓값을 제시하기 때문에 네이버 및 증권사별로 상이할것 같습니다.
컨센서스를 확인해서 참고만 하면 될것 같습니다..

**Comment by Yoodahun** [comment]
@kimhankyeol 감사합니다. 책의 다음판이 인쇄될때 이 부분이 수정되면 좋을 것 같아요! 감사합니다 :)
