### ISSUE TITLE
234p sql과 연결 부분 질문입니다.

### ISSUE THREAD

**Issue by kyunkyun94** [hyunyulhenry/quant_py#5]
책 내용대로 따라가고 있는데 해당 부분의 에러가 해결되지 않아 질문드립니다. 어떤 부분이 잘못된걸까요? sql에도 테이블이 잘 나오고 있고, kor_ticker 에도 책과 동일한 테이블이 들어있는데 계속 아래 에러가 뜨는 상황입니다.

![image](https://user-images.githubusercontent.com/37871628/224557483-05c5de80-e870-4efb-aef5-b29e86dc00d4.png)
![image](https://user-images.githubusercontent.com/37871628/224557495-be2bcd9c-00c9-4c28-97c2-ed5b28a94abe.png)
![image](https://user-images.githubusercontent.com/37871628/224557532-30809875-684d-49a1-be6e-3bdf6cbd8227.png)

**Comment by hyunyulhenry** [comment]
![image](https://user-images.githubusercontent.com/20567847/224584358-fcf9f440-1f06-4c85-b8b9-3ad56cd96d9d.png)

원하는 열만 선택하는 부분이 빠져있습니다.
그래서 파이썬의 열 갯수와 SQL의 열 갯수가 매치되지 않아 오류가 발생하는 겁니다.

**Comment by kyunkyun94** [comment]
답변감사합니다! 손으로 직접 치면서 하다보니 빼먹은 코드가 있었네요ㅜ

**Comment by hyunyulhenry** [comment]
직접 입력해보는게 좋은 습관이죠 ㅎㅎ
