### ISSUE TITLE
KRX 업종 분류 현황 크롤링 관련 질문

### ISSUE THREAD

**Issue by ghost** [hyunyulhenry/quant_py#50]
```
gen_otp_url = 'http://data.krx.co.kr/comm/fileDn/GenerateOTP/generate.cmd'
gen_otp_stk = {
    'mktId': 'STK',
    'trdDd': biz_day,
    'money': '1',
    'csvxls_isNo': 'false',
    'name': 'fileDown',
    'url': 'dbms/MDC/STAT/standard/MDCSTAT03901'
}
headers = {'Referer': 'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader'}
otp_stk = rq.post(gen_otp_url, gen_otp_stk, headers=headers).text

print(otp_stk)
```
오늘 새벽에 제가 멀티팩터 종목을 만들어볼려고 평소와 같이 실행했는데요

에러코드가 나와서 해당부분을 살펴봤습니다.

그렇게 위에 나와있는 부분을 때서 프린트 하면 OTP 코드가 나와야 하는데 HTML 에러코드가 나오네요
제 생각에는 KRX에서 이 부분을 막아 놓은것 같은 그런 느낌인데요.

이 부분 어떻게 해야할까요?

**Comment by scotthan10** [comment]
네 저도 같은 문제가 발생했습니다. 7/5(금) 까지 이상 없었는데, 그 이후로 에러가 나옵니다.
혹시 해결방법이 있으시면 공유부탁드립니다. 미리 감사드립니다.

**Comment by kimhankyeol** [comment]
다른 문제는 아니고 헤더 부분에
headers = {'Referer':'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader','Upgrade-Insecure-Requests': '1','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'}

User-Agent는 generate.cmd 부분에 header를 참조해서 바꿔주세요
그러면 정상 조회 되실겁니다

**Comment by H9-Develop** [comment]
headers = {'Referer':'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader','Upgrade-Insecure-Requests': '1','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'}
헤더 부분에 2개 추가 해주시고 User-Agent 부분은 generate.cmd 에서 참고해서 바꿔주세요.
그러면 정상조회 됩니다.

**Comment by jungyh2356** [comment]
대단히 감사합니다 ㅠㅠ

**Comment by ghost** [comment]
조언주신대로 
```
headers={'Referer':'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader',
         'Upgrade-Insecure-Requests':'1',
         'User-Agent':'Mozilla/5.0'}

```
이렇게 입력하고 otp_stk를 print해봤는데 <Response [400]>에러가 뜨네요... 이거 어찌해야하나요 ㅠ

**Comment by H9-Develop** [comment]
url 이나 stk 부분 잘못쓰여진게 없는지 확인해주세요. 문법이나 잘못된 요청으로 뜨는거에요

**Comment by ghost** [comment]
해결되었습니다. 감사합니다.
