### ISSUE TITLE
10.5.2 전 종목 재무제표 크롤링 후 DB 저장 안됨

### ISSUE THREAD

**Issue by byfaith2000** [hyunyulhenry/quant_py#52]
안녕하세요.
책으로 공부 잘하고 있습니다. 
253페이지 전 종목 재무제표 크롤링에서 책에 있는대로 모두 코딩 후 실행하면 
콘솔창에 아래와 같이 크롤링이 잘 되는 것 같은데 실제 my sql에서 kor_fs 테이블을
확인하면  columns(계정, 기준일, 값, 종목코드, 공시구분)만 보이고 각 column 값들은
NULL로 뜹니다. 왜 그러는걸까요???ㅜㅜ
진행률 100%까지 완료해도 마찬가지에요...

 0%|          | 0/2433 [00:00<?, ?it/s]000020
  0%|          | 1/2433 [00:03<2:22:44,  3.52s/it]000040
  0%|          | 2/2433 [00:06<2:20:50,  3.48s/it]000050
  0%|          | 3/2433 [00:10<2:13:14,  3.29s/it]000070
  0%|          | 4/2433 [00:13<2:10:30,  3.22s/it]000080
  0%|          | 5/2433 [00:16<2:08:57,  3.19s/it]000100
  0%|          | 6/2433 [00:19<2:07:24,  3.15s/it]000120
  0%|          | 7/2433 [00:22<2:07:03,  3.14s/it]000140
  0%|          | 8/2433 [00:25<2:05:59,  3.12s/it]000150
  0%|          | 9/2433 [00:28<2:09:37,  3.21s/it]000180
  0%|          | 10/2433 [00:32<2:07:58,  3.17s/it]000210
  0%|          | 11/2433 [00:35<2:06:30,  3.13s/it]000220
  0%|          | 12/2433 [00:38<2:05:59,  3.12s/it]000230
  1%|          | 13/2433 [00:41<2:05:14,  3.11s/it]000240
  1%|          | 14/2433 [00:44<2:09:16,  3.21s/it]000250
  1%|          | 15/2433 [00:47<2:06:54,  3.15s/it]000270
  1%|          | 16/2433 [00:50<2:06:12,  3.13s/it]000300
  1%|          | 17/2433 [00:53<2:04:47,  3.10s/it]000320
  1%|          | 18/2433 [00:56<2:04:09,  3.08s/it]000370
  1%|          | 19/2433 [01:00<2:05:50,  3.13s/it]000390
  1%|          | 20/2433 [01:03<2:04:39,  3.10s/it]000400
  1%|          | 21/2433 [01:06<2:09:25,  3.22s/it]000430
  1%|          | 21/2433 [07:27<14:16:25, 21.30s/it]

**Comment by hong8282** [comment]
저도 동일한 증상이 발생합니다.
제가 코드를 잘못 작성했나 하여 교수님이 올려주신 코드를 돌려봤는데 mysql 에 저장이 안되더라구요
확인 부탁드립니다 ^^

**Comment by hyunyulhenry** [comment]
for 구문으로 돌리기 전에 하나씩 확인해보면 어디서 오류가 발생하는지 알 수 있습니다.
