### ISSUE TITLE
안녕하세요 10.4.1 개별종목 주가 크롤링 문의사항 입니다.

### ISSUE THREAD

**Issue by HB1065** [hyunyulhenry/quant_py#56]
네이버에 접속 후
--> 개발자 도구화면 --> 네트워크 화면 들어가서 보면

[siseJson.naver?symbol=..] 항목이 안보입니다. 

제가 뭔가 잘 못한것 아닌 것 같고
페이지에 뭔가 변화가 있는건가요??

**Comment by HB1065** [comment]
[화면 캡쳐.pdf](https://github.com/user-attachments/files/18226957/default.pdf)

**Comment by hyunyulhenry** [comment]
![image](https://github.com/user-attachments/assets/09b857c3-ad76-4150-9ae1-070987828ca5)

`info?symbol ` 로 변경되었네요
