### ISSUE TITLE
p.347 오타

### ISSUE THREAD

**Issue by GritUpward** [hyunyulhenry/quant_py#6]
p.347 부분에서

select * from kor_setor 이후
where 기준일 = (select max(기준일) from **kor_ticker**) ;

해당 부분에서
from kor_sector 로 변경해야 될 듯합니다.

**Comment by hyunyulhenry** [comment]
아 그러네요 감사합니다!

**Comment by GritUpward** [comment]
p.355 멀티팩터 포트폴리오 부분에서도 동일한듯합니다~

**Comment by hyunyulhenry** [comment]
넹 안그래도 이부분도 체크해뒀습니다.
