### ISSUE TITLE
Mac 에서 MySQL Workbench SELECT문 호출 시 세션이 닫히는 경우

### ISSUE THREAD

**Issue by ico1036** [hyunyulhenry/quant_py#7]
Mac book air M1 에서 MySQL Workbench를 설치하고 SELECT 문을 호출했을 때 세션이 닫히는 에러가 있습니다.
현 최신 Workbench 버전은 8.0.33 인데, 8.3.30 으로 down grade 하니 작동 됩니다.

**Comment by hyunyulhenry** [comment]
아 감사합니다. 안그래도 학교 수업에서도 이거 오류나는 학생들 있던데 다음쇄에 공지사항으로 넣도록 하겠습니다.
