### ISSUE TITLE
'list' object has no attribute 'shape'  에러입니다

### ISSUE THREAD

**Issue by hojune2** [hyunyulhenry/quant_py#8]
![스크린샷 2023-03-30 154428](https://user-images.githubusercontent.com/129351393/228752168-fe100403-c563-49eb-abc4-243e979ff3b3.png)

요렇게 나옵니다. 위험균형 포트폴리오까지는 잘 됐는데 위험 예산포트폴리오만 안됩니다 ㅠ
파이썬 업데이트도 해보고 array로 바꿔서도 해보고
 갈아엎고 아예 처음부터 새로운 노트북 만들어서 다시해도 안되네요 ㅠ

**Comment by hyunyulhenry** [comment]
혹시 riskfolio 버젼이 몇이죠?
그리고 작성하신 코드는 캡쳐 말고 텍스트로도 적어주시겠어요

**Comment by hojune2** [comment]
riskfolio 버전은 4.1.0이고
위험예산이 위험균형이랑 연결돼서 위험균형 코드까지 적어보면 이렇게 입니다.

#위험균형
port= rp.Portfolio(returns=rets)
method_mu='hist'
method_cov='hist'
port.assets_stats(method_mu=method_mu, method_cov=method_cov)

model='Classic'
rm='MV'
hist=True
rf=0
b=None
w_rp=port.rp_optimization(model=model,rm=rm,rf=rf,b=b,hist=hist)
w_rp.T

#위험예산
b=[0.15,0.15,0.15,0.15,0.1,0.1,0.05,0.05,0.05,0.05]
w_rp= port.rp_optimization(model=model, rm=rm,rf=rf,b=b,hist=hist)
w_rp.T

**Comment by hyunyulhenry** [comment]
제꺼에선 잘 돌아가네요...

```
pip install riskfolio-lib==3.3.0
```

이렇게 버젼 내리고 한번 다시 돌려보시겠어요?

**Comment by hojune2** [comment]
아 버전을 낮추니까 되네요 !! 어제 이것 때문에 하루종일 고생했는데
정말 감사합니다 ㅠㅠ

**Comment by hojune2** [comment]
아 버전을 낮추니까 되네요 !!
정말 감사합니다 ㅠㅠ

**Comment by devgony** [comment]
저같은 경우는 `riskfolio-lib = "^5.0.1"` 사용하고 있는데
`3.3.0` 으로 낮추면 #18 에서 막힙니다. (`pandas = "^2.2.1"` 와 충돌)
그래서 버전을 낮추는것보다는 `5.0.1` 로 그대로 두고 코드를 수정하였습니다.
```py
import numpy as np

b = np.array([0.15, 0.15, 0.15, 0.15, 0.10, 0.10, 0.05, 0.05, 0.05, 0.05]).reshape(-1, 1)
w_rp = port.rp_optimization(model=model, rm=rm, rf=rf, b=b, hist=hist)

w_rp.T
```
