### ISSUE TITLE
pip install riskfolio-lib==3.3.0 오류... 문의

### ISSUE THREAD

**Issue by GritUpward** [hyunyulhenry/quant_py#9]
안녕하세요 대표님 책과 유툽으로 부지런히 공부하고 많이 배우고 있습니다!

14장 포트폴리오 구성 전략을 진행을 해야되는데
pip install riskfolio-lib==3.3.0 해당 부분에서 오류로 시작을 못하고 있습니다.

유튜브에 나와있는 대로 cvxpy 부분이 설치가 안되있어 구글링하여 열심히 해봤지만
결국 .whl 파일을 구해서 나름 진행이 된듯하지만

후에 다시 pip 으로 진행을 해봐도 계속 막히더라구요..
이틀이 넘게 진행을 못하고 있어서

많이 바쁘시겠지만 답답한 마음에 도움을 받고자 문의 드립니다.

-------------------------------------------------------------------------------------------------------------------------------------------
C:\Users\Grit_Upward\Desktop\Grit_Upward>pip install riskfolio-lib==3.3.0
Collecting riskfolio-lib==3.3.0
  Using cached Riskfolio_Lib-3.3.0-py3-none-any.whl (90 kB)
Requirement already satisfied: scipy>=1.0.1 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (1.7.3)
Collecting arch>=4.15
  Using cached arch-5.3.1-cp39-cp39-win32.whl (814 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (1.21.5)
Requirement already satisfied: statsmodels>=0.10.1 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (0.13.2)
Requirement already satisfied: xlsxwriter>=1.3.7 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (3.0.3)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (1.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (3.5.1)
Requirement already satisfied: networkx>=2.5.1 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (2.7.1)
Requirement already satisfied: pandas>=1.0.0 in c:\users\grit_upward\appdata\roaming\python\python39\site-packages (from riskfolio-lib==3.3.0) (1.4.1)
Requirement already satisfied: astropy>=4.3.1 in c:\anaconda3\lib\site-packages (from riskfolio-lib==3.3.0) (5.0.4)
Collecting cvxpy>=1.0.25
  Using cached cvxpy-1.3.1-cp39-cp39-win32.whl
Requirement already satisfied: property-cached>=1.6.4 in c:\anaconda3\lib\site-packages (from arch>=4.15->riskfolio-lib==3.3.0) (1.6.4)
Requirement already satisfied: pyerfa>=2.0 in c:\anaconda3\lib\site-packages (from astropy>=4.3.1->riskfolio-lib==3.3.0) (2.0.0)
Requirement already satisfied: PyYAML>=3.13 in c:\anaconda3\lib\site-packages (from astropy>=4.3.1->riskfolio-lib==3.3.0) (6.0)
Requirement already satisfied: packaging>=19.0 in c:\anaconda3\lib\site-packages (from astropy>=4.3.1->riskfolio-lib==3.3.0) (21.3)
Requirement already satisfied: scs>=1.1.6 in c:\anaconda3\lib\site-packages (from cvxpy>=1.0.25->riskfolio-lib==3.3.0) (3.2.2)
Collecting osqp>=0.4.1
  Using cached osqp-0.6.2.post8.tar.gz (227 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-67.6.1-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
      Collecting qdldl
        Using cached qdldl-0.1.5.post3.tar.gz (69 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3-cp39-cp39-win32.whl (11.0 MB)
      Collecting packaging>=20.0
        Using cached packaging-23.0-py3-none-any.whl (42 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting typing-extensions
        Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
      Collecting scipy>=0.13.2
        Using cached scipy-1.10.1.tar.gz (42.4 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1
      
        [37 lines of output]
        + meson setup --prefix=C:\anaconda3 C:\Users\Grit_Upward\AppData\Local\Temp\pip-install-c94p7j4m\scipy_ce8926b2efa9402fbba293eb9115979b C:\Users\Grit_Upward\AppData\Local\Temp\pip-install-c94p7j4m\scipy_ce8926b2efa9402fbba293eb9115979b\.mesonpy-olf21y77\build --native-file=C:\Users\Grit_Upward\AppData\Local\Temp\pip-install-c94p7j4m\scipy_ce8926b2efa9402fbba293eb9115979b\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
        The Meson build system
        Version: 1.0.1
        Source dir: C:\Users\Grit_Upward\AppData\Local\Temp\pip-install-c94p7j4m\scipy_ce8926b2efa9402fbba293eb9115979b
        Build dir: C:\Users\Grit_Upward\AppData\Local\Temp\pip-install-c94p7j4m\scipy_ce8926b2efa9402fbba293eb9115979b\.mesonpy-olf21y77\build
        Build type: native build
        Project name: SciPy
        Project version: 1.10.1
        Activating VS 17.5.3
        C compiler for the host machine: cl (msvc 19.35.32216.1 "Microsoft (R) C/C++ 최적화 컴파일러 버전 19.35.32216.1(x64)")
        C linker for the host machine: link link 14.35.32216.1
        C++ compiler for the host machine: cl (msvc 19.35.32216.1 "Microsoft (R) C/C++ 최적화 컴파일러 버전 19.35.32216.1(x64)")
        C++ linker for the host machine: link link 14.35.32216.1
        Cython compiler for the host machine: cython (cython 0.29.33)
        Host machine cpu family: x86_64
        Host machine cpu: x86_64
        Compiler for C supports arguments -Wno-unused-but-set-variable: NO
        Compiler for C supports arguments -Wno-unused-function: NO
        Compiler for C supports arguments -Wno-conversion: NO
        Compiler for C supports arguments -Wno-misleading-indentation: NO
        Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
        Library m found: NO

        ..\..\meson.build:63:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
        The following exception(s) were encountered:
        Running `ifort --version` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `ifort -V` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `gfortran --version` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `gfortran -V` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `flang --version` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `flang -V` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `pgfortran --version` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `pgfortran -V` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `g95 --version` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"
        Running `g95 -V` gave "[WinError 2] 지정된 파일을 찾을 수 없습니다"

        A full log can be found at C:\Users\Grit_Upward\AppData\Local\Temp\pip-install-c94p7j4m\scipy_ce8926b2efa9402fbba293eb9115979b\.mesonpy-olf21y77\build\meson-logs\meson-log.txt
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

---------------------------------------------------------------------------------------------------------------------------------------

위 내용이 오류 전문입니다. 너그러운 양해 부탁드립니다.

**Comment by hyunyulhenry** [comment]
정확히는 모르겠지지만 `Installing build dependencies ... error` 이걸 봐선 Dependencies 패키지 설치하다가 뻑나는거 같습니다.
riskfolio의 디펜던시 패키지는 다음과 같습니다.
하나씩 제대로 설치 되었는지, 버젼 맞는지 체크해보셔야 될 거 같네요.

![image](https://user-images.githubusercontent.com/20567847/229132031-d310208d-224f-41eb-a09e-41fc956e606b.png)
https://riskfolio-lib.readthedocs.io/en/latest/install.html#dependencies

**Comment by GritUpward** [comment]
늘 감사드립니다.
———————————————————————————

2023년 3월 31일 (금) 오후 10:25, HenryLee ***@***.***>님이 작성:
